[package]
name = "reaktor_fast_track_2"
version = "0.0.2"
authors = [ "Ville Peurala <ville.peurala@gmail.com>" ]

[dependencies]
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"
serde_test = "1.0.24"

[[bin]]
name = "reaktor_fast_track_2"
